local telescope = require("telescope.builtin")
vim.keymap.set("n", "<leader><leader>", function() telescope.find_files() end, { desc = "Find file" })
vim.keymap.set("n", "<leader>fg", function() telescope.live_grep() end, { desc = "Grep in files" })
vim.keymap.set("n", "<leader>fb", function() telescope.buffers() end, { desc = "Find buffer" })
vim.keymap.set("n", "<leader>fh", function() telescope.help_tags() end, { desc = "Find help" })
vim.keymap.set("n", "<leader>fr", function() telescope.oldfiles() end, { desc = "Find recent files" })
vim.keymap.set("n", "<leader>fs", function() telescope.lsp_document_symbols() end, { desc = "Find symbols" })
vim.keymap.set("n", "<leader>fw", function() telescope.grep_string() end, { desc = "Find word under cursor" })
